version: "3.7"

services:
    backend:
        build: .
        ports:
            - 5000:5000
        networks:
            - default
        depends_on:
            - db

    db:
        image: mdillon/postgis
        environment:
            - POSTGRES_PASSWORD="mysecretpassword"
        networks:
            - default
        volumes:
            - ./postgresql:/var/lib/postgresql
        ports:
            - 5432:5432